import FuzzySearch from 'fuzzy-search';
import { VEGETABLE_ICONS } from "./vegetables";

const mapping: {id: keyof typeof VEGETABLE_ICONS, translation: string}[] = [
  { "id": "acornSquash", "translation": "courge gland" },
  { "id": "almond", "translation": "amande" },
  { "id": "apricot", "translation": "abricot" },
  { "id": "arugula", "translation": "roquette" },
  { "id": "asianPear", "translation": "poire asiatique" },
  { "id": "asparagus", "translation": "asperge" },
  { "id": "atrichoke", "translation": "artichaut" },
  { "id": "barley", "translation": "orge" },
  { "id": "basil", "translation": "basilic" },
  { "id": "beet", "translation": "betterave" },
  { "id": "belgianEndive", "translation": "endive" },
  { "id": "bibbLettuce", "translation": "laitue Bibb" },
  { "id": "bingCherry", "translation": "cerise Bing" },
  { "id": "blackHabanero", "translation": "habanero noir" },
  { "id": "blackPrinceTomato", "translation": "tomate Black Prince" },
  { "id": "blackSalsify", "translation": "salsifis noir" },
  { "id": "blackberry", "translation": "mûre" },
  { "id": "blueLakeBean", "translation": "haricot Blue Lake" },
  { "id": "blueOyster", "translation": "huître bleue" },
  { "id": "blueberry", "translation": "myrtille" },
  { "id": "bokChoy", "translation": "bok choy" },
  { "id": "borage", "translation": "bourrache" },
  { "id": "broadBean", "translation": "fève" },
  { "id": "broccoli", "translation": "brocoli" },
  { "id": "brusselSprout", "translation": "chou de Bruxelles" },
  { "id": "butternutSquash", "translation": "courge musquée" },
  { "id": "californiaPoppy", "translation": "pavot de Californie" },
  { "id": "cannabis", "translation": "cannabis" },
  { "id": "cantaloupe", "translation": "cantaloup" },
  { "id": "carrot", "translation": "carotte" },
  { "id": "cauliflower", "translation": "chou fleur" },
  { "id": "celeriacRoot", "translation": "céleri celeri rave" },
  { "id": "celery", "translation": "céleri celeri" },
  { "id": "chamomile", "translation": "camomille" },
  { "id": "chantrelle", "translation": "chanterelle" },
  { "id": "cherryBellRadish", "translation": "radis Cherry Bell" },
  { "id": "cilantro", "translation": "coriandre" },
  { "id": "claytonia", "translation": "claytonie" },
  { "id": "collardGreens", "translation": "chou cavalier" },
  { "id": "corn", "translation": "maïs mais" },
  { "id": "cotton", "translation": "coton" },
  { "id": "cremini", "translation": "crémini" },
  { "id": "cucumber", "translation": "concombre" },
  { "id": "curlyKale", "translation": "chou frisé frise" },
  { "id": "dandelion", "translation": "pissenlit" },
  { "id": "delicataSquash", "translation": "courge delicata" },
  { "id": "dill", "translation": "aneth" },
  { "id": "echinacea", "translation": "échinacée" },
  { "id": "eggplant", "translation": "aubergine" },
  { "id": "fennel", "translation": "fenouil" },
  { "id": "frenchBreakfastRadish", "translation": "radis French Breakfast" },
  { "id": "fujiApple", "translation": "pomme Fuji" },
  { "id": "galaApple", "translation": "pomme Gala" },
  { "id": "galangal", "translation": "galanga" },
  { "id": "garlic", "translation": "ail" },
  { "id": "garlicChive", "translation": "ciboulette" },
  { "id": "genericApple", "translation": "pomme" },
  { "id": "genericFlower", "translation": "fleur" },
  { "id": "genericMelon", "translation": "melon" },
  { "id": "genericMushroom", "translation": "champignon" },
  { "id": "genericPlant", "translation": "plante" },
  { "id": "germanChamomile", "translation": "camomille allemande" },
  { "id": "ginger", "translation": "gingembre" },
  { "id": "goldenBeet", "translation": "betterave dorée" },
  { "id": "goldenDeliciousApple", "translation": "pomme Golden Delicious" },
  { "id": "grannySmithApple", "translation": "pomme Granny Smith" },
  { "id": "greenAnjouPear", "translation": "poire Anjou verte" },
  { "id": "greenBartlettPear", "translation": "poire Bartlett verte" },
  { "id": "greenBellPepper", "translation": "poivron vert" },
  { "id": "greenCabbage", "translation": "chou vert" },
  { "id": "greenOnion", "translation": "oignon vert" },
  { "id": "hemp", "translation": "chanvre" },
  { "id": "honeydew", "translation": "melon miel" },
  { "id": "hop", "translation": "houblon" },
  { "id": "iceberg", "translation": "laitue Iceberg" },
  { "id": "icicleRadish", "translation": "radis glaçon" },
  { "id": "indigo", "translation": "indigo" },
  { "id": "jalapeno", "translation": "jalapeño" },
  { "id": "japaneseYam", "translation": "igname japonaise" },
  { "id": "kabochaSquash", "translation": "courge kabocha" },
  { "id": "kohlrabi", "translation": "chou rave" },
  { "id": "laciantoKale", "translation": "chou kale lacinato" },
  { "id": "lavender", "translation": "lavande" },
  { "id": "leek", "translation": "poireau" },
  { "id": "lemonBalm", "translation": "mélisse" },
  { "id": "lemonVerbena", "translation": "verveine citronnelle" },
  { "id": "lemongrass", "translation": "citronnelle" },
  { "id": "limaBean", "translation": "fève de Lima" },
  { "id": "lionsMane", "translation": "crinière de lion" },
  { "id": "looseLeafLettuce", "translation": "laitue à feuilles lâches" },
  { "id": "lovage", "translation": "livèche" },
  { "id": "majoram", "translation": "marjolaine" },
  { "id": "marshmallow", "translation": "guimauve" },
  { "id": "mint", "translation": "menthe" },
  { "id": "moneyTree", "translation": "arbre à monnaie" },
  { "id": "mugwort", "translation": "armoise" },
  { "id": "napaCabbage", "translation": "chou napa" },
  { "id": "nectratine", "translation": "nectarine" },
  { "id": "oat", "translation": "avoine" },
  { "id": "okra", "translation": "gombo" },
  { "id": "onionChive", "translation": "ciboulette" },
  { "id": "orangeBellPepper", "translation": "poivron orange" },
  { "id": "oregano", "translation": "origan" },
  { "id": "ornamentalGourd", "translation": "courge ornementale" },
  { "id": "parsley", "translation": "persil" },
  { "id": "parsnip", "translation": "panais" },
  { "id": "pattypanSquash", "translation": "courge pattypan" },
  { "id": "peach", "translation": "pêche peche" },
  { "id": "peanut", "translation": "cacahuète" },
  { "id": "pinkOyster", "translation": "huître rose" },
  { "id": "plantain", "translation": "plantain" },
  { "id": "plum", "translation": "prune" },
  { "id": "pointedCabbage", "translation": "chou pointu" },
  { "id": "porcino", "translation": "cèpe" },
  { "id": "portabello", "translation": "portobello" },
  { "id": "psilocybin", "translation": "psilocybine" },
  { "id": "pumpkin", "translation": "citrouille" },
  { "id": "purpleCarrot", "translation": "carotte violette" },
  { "id": "purpleCauliflower", "translation": "chou fleur violet" },
  { "id": "purplePodBean", "translation": "haricot à cosse violette" },
  { "id": "purplePotato", "translation": "pomme de terre patate violette" },
  { "id": "radicchio", "translation": "radicchio" },
  { "id": "rainierCherry", "translation": "cerise Rainier" },
  { "id": "raspberry", "translation": "framboise" },
  { "id": "redAnjouPear", "translation": "poire Anjou rouge" },
  { "id": "redBartlettPear", "translation": "poire Bartlett rouge" },
  { "id": "redBellPepper", "translation": "poivron rouge" },
  { "id": "redCabbage", "translation": "chou rouge" },
  { "id": "redCarrot", "translation": "carotte rouge" },
  { "id": "redChard", "translation": "bette rouge" },
  { "id": "redCurlyKale", "translation": "chou frise frisé rouge" },
  { "id": "redGiantMustard", "translation": "moutarde géante rouge" },
  { "id": "redGoldPotato", "translation": "pomme de terre patate Red Gold" },
  { "id": "redKuriSquash", "translation": "potiron Red Kuri" },
  { "id": "redOnion", "translation": "oignon rouge" },
  { "id": "redPointedCabbage", "translation": "chou pointu rouge" },
  { "id": "redRussianKale", "translation": "chou kale russe rouge" },
  { "id": "rice", "translation": "riz" },
  { "id": "romaine", "translation": "laitue romaine" },
  { "id": "rosemary", "translation": "romarin" },
  { "id": "runnerBean", "translation": "haricot Espagne" },
  { "id": "russetPotato", "translation": "pomme de terre patate Russet" },
  { "id": "rutabaga", "translation": "rutabaga" },
  { "id": "rye", "translation": "seigle" },
  { "id": "sage", "translation": "sauge" },
  { "id": "salsify", "translation": "salsifis" },
  { "id": "savoyCabbage", "translation": "chou de Savoie" },
  { "id": "shallot", "translation": "échalote echalote" },
  { "id": "shiitake", "translation": "shiitake" },
  { "id": "snapPea", "translation": "pois mange-tout" },
  { "id": "sorghumMillet", "translation": "mil de sorgho" },
  { "id": "soyBean", "translation": "soja" },
  { "id": "spaghettiSquash", "translation": "courge spaghetti" },
  { "id": "spinach", "translation": "épinard" },
  { "id": "springOnion", "translation": "oignon de printemps" },
  { "id": "stJohnsWort", "translation": "millepertuis" },
  { "id": "strawberry", "translation": "fraise" },
  { "id": "sugarCane", "translation": "canne à sucre" },
  { "id": "sunflower", "translation": "tournesol" },
  { "id": "sweetPotato", "translation": "patate douce" },
  { "id": "swissChard", "translation": "bette à carde" },
  { "id": "thyme", "translation": "thym" },
  { "id": "tomatillo", "translation": "tomatillo" },
  { "id": "tomato", "translation": "tomate" },
  { "id": "trumpet", "translation": "trompette" },
  { "id": "tulsi", "translation": "tulsi" },
  { "id": "turmeric", "translation": "curcuma" },
  { "id": "turnip", "translation": "navet" },
  { "id": "watercress", "translation": "cresson" },
  { "id": "watermelon", "translation": "pastèque pasteque" },
  { "id": "watermelonRadish", "translation": "radis pastèque" },
  { "id": "waxBean", "translation": "haricot cire" },
  { "id": "wheat", "translation": "blé" },
  { "id": "whiteButton", "translation": "champignon blanc" },
  { "id": "whiteCarrot", "translation": "carotte blanche" },
  { "id": "whiteOnion", "translation": "oignon blanc" },
  { "id": "whiteOyster", "translation": "huître blanche" },
  { "id": "wormwood", "translation": "absinthe" },
  { "id": "yellowBellPepper", "translation": "poivron jaune" },
  { "id": "yellowCarrot", "translation": "carotte jaune" },
  { "id": "yellowCauliflower", "translation": "chou fleur jaune" },
  { "id": "yellowOnion", "translation": "oignon jaune" },
  { "id": "yellowOyster", "translation": "huître jaune" },
  { "id": "yellowSquash", "translation": "courge jaune" },
  { "id": "youkonGoldPotato", "translation": "pomme de terre patate Yukon Gold" },
  { "id": "zucchini", "translation": "courgette" }
];

const searcher = new FuzzySearch(mapping, ['translation'], {
  caseSensitive: false,
  sort:true,
});

export const searchVegetable = (str: string) => {
  const result = searcher.search(str);
  return result[0]?.id ?? undefined;
}

export const searchVegetables = (str: string) => {
  return searcher.search(str).map(({id}) => id);
}